name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dd4ae31a8493e43ca236e501a3f3e53114f1d02bebdcadfde86505aebb8ce00"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
