name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02388e5755452190f99f49eab741e749b9eee3ed8b56946d2ba4c8831c0c96f5"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
