name = "Create Astral"
author = "Laskyyy"
version = "v2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11b165b7cc61a9ef64c558576a72f9bb487f9e9122870ce3bd1d35be4cae1b11"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
